common: &common
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script: >
      echo $CIRRUS_TASK_NAME:$CIRRUS_OS:$RUBY_VERSION &&
      cat Gemfile &&
      cat *.gemspec
    populate_script: bundle install

  test_script: bundle exec rake


task:
  name: Test (Linux)
  container:
    matrix:
      image: ruby:2.3
      image: ruby:2.4
      image: ruby:2.5
      image: jruby:latest
  <<: *common

task:
  name: Test (Windows)
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  <<: *common

task:
  name: Test (macOS)
  osx_instance:
    image: mojave-base
  <<: *common
