language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.9.0

os:
  - linux
  - osx

# https://github.com/travis-ci/travis-ci/issues/1147#issuecomment-160820262
branches:
  only:
  - master

before_install:
  - gem update --system
  - gem install bundler

cache:
  - bundler
  - directories:
    - /home/travis/.rvm/
