language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.9.0

os:
  - linux
  - osx

before_install:
  - gem update --system
  - gem install bundler

cache:
  - bundler
  - directories:
    - /home/travis/.rvm/
